# JSON for Data Engineering

## Understanding JSON Format, Objects, Arrays, Data Types, GeoJSON, and Python `json`

JSON is one of the most common data formats used in APIs, configuration files, logs, and modern data pipelines.

## 1. What Does JSON Look Like?

Here is a simple JSON example:

```json
{
  "name": "Alice",
  "age": 25,
  "is_student": true,
  "skills": ["Python", "SQL", "Data Engineering"]
}
```

Question:

Which parts are:

1. Keys?
2. Values?
3. String values?
4. Number values?
5. Boolean values?
6. Array values?

In [ ]:
import json

demo_json = {
    "string_value": "Alice",
    "integer_value": 25,
    "float_value": 3.14,
    "boolean_true": True,
    "boolean_false": False,
    "null_value": None,
    "array_value": ["Python", 42, True, None],
    "nested_object": {
        "city": "Singapore",
        "population": 5900000
    }
}

print(json.dumps(demo_json, indent=2, ensure_ascii=False))

In [ ]:
data = {}

### Answer

| JSON Part | Example |
|---|---|
| Key | `"name"`, `"age"`, `"is_student"`, `"skills"` |
| String value | `"Alice"` |
| Number value | `25` |
| Boolean value | `true` |
| Array value | `["Python", "SQL", "Data Engineering"]` |

Note:

> JSON stores data using key-value pairs, arrays, and simple data types.

## 2. JSON Object

A JSON object is written using curly braces `{}`.

It contains key-value pairs.

Example:

```json
{
  "region": "Central",
  "taxi_count": 120,
  "weather": "Cloudy"
}
```

In Python, a JSON object is usually converted into a dictionary.

In [1]:
import json
import pandas as pd
from pprint import pprint

In [2]:
json_text = '''
{
  "region": "Central",
  "taxi_count": 120,
  "weather": "Cloudy"
}
'''

data = json.loads(json_text)

print(type(data))
pprint(data)

<class 'dict'>
{'region': 'Central', 'taxi_count': 120, 'weather': 'Cloudy'}

## 3. JSON Array

A JSON array is written using square brackets `[]`.

Example:

```json
[
  "Central",
  "East",
  "West"
]
```

In Python, a JSON array is usually converted into a list.

In [3]:
json_text = '''
[
  "Central",
  "East",
  "West"
]
'''

data = json.loads(json_text)

print(type(data))
pprint(data)

<class 'list'>
['Central', 'East', 'West']

## 4. Object vs Array

This is one of the most important beginner concepts.

| JSON Structure | Syntax | Python Type | Meaning |
|---|---|---|---|
| Object | `{}` | `dict` | One structured record |
| Array | `[]` | `list` | A collection of values or records |

Example:

```json
{
  "station": "S001",
  "temperature": 30.5
}
```

This is one object.

```json
[
  {"station": "S001", "temperature": 30.5},
  {"station": "S002", "temperature": 31.2}
]
```

This is an array of objects.

In [4]:
json_text = '''
[
  {"station": "S001", "temperature": 30.5},
  {"station": "S002", "temperature": 31.2},
  {"station": "S003", "temperature": 29.8}
]
'''

weather_data = json.loads(json_text)

print(type(weather_data))
print(type(weather_data[0]))
pprint(weather_data[0])

<class 'list'>
<class 'dict'>
{'station': 'S001', 'temperature': 30.5}

## 5. JSON Data Types

JSON supports a small set of data types.

| JSON Type | Example | Python Type |
|---|---|---|
| String | `"Singapore"` | `str` |
| Number | `123`, `30.5` | `int`, `float` |
| Boolean | `true`, `false` | `True`, `False` |
| Null | `null` | `None` |
| Object | `{ "a": 1 }` | `dict` |
| Array | `[1, 2, 3]` | `list` |

Important differences between JSON and Python:

| JSON | Python |
|---|---|
| `true` | `True` |
| `false` | `False` |
| `null` | `None` |
| double quotes required | Python allows single or double quotes for strings |

In [5]:
json_text = '''
{
  "city": "Singapore",
  "temperature": 30.5,
  "rain": false,
  "warning": null,
  "forecast": ["Cloudy", "Rain", "Fair"],
  "metadata": {
    "source": "sample_api",
    "unit": "Celsius"
  }
}
'''

data = json.loads(json_text)

for key, value in data.items():
    print(key, "=>", value, "| Python type:", type(value))

city => Singapore | Python type: <class 'str'>
temperature => 30.5 | Python type: <class 'float'>
rain => False | Python type: <class 'bool'>
warning => None | Python type: <class 'NoneType'>
forecast => ['Cloudy', 'Rain', 'Fair'] | Python type: <class 'list'>
metadata => {'source': 'sample_api', 'unit': 'Celsius'} | Python type: <class 'dict'>

## 6. Valid JSON vs Invalid JSON

JSON has strict syntax rules.

Common rules:

1. Keys must be strings with double quotes.
2. String values must use double quotes.
3. No trailing comma.
4. Comments are not allowed.
5. Boolean values are lowercase: `true`, `false`.
6. Null value is lowercase: `null`.

The following is valid JSON:

```json
{
  "name": "Alice",
  "age": 25
}
```

The following is invalid JSON:

```json
{
  name: "Alice",
  "age": 25,
}
```

Problems:

- `name` has no double quotes.
- There is a trailing comma after `25`.

In [6]:
# Valid JSON

valid_json = '''
{
  "name": "Alice",
  "age": 25
}
'''

data = json.loads(valid_json)
pprint(data)

{'age': 25, 'name': 'Alice'}

In [7]:
# Invalid JSON example
# Run this cell and observe the error message.

invalid_json = '''
{
  name: "Alice",
  "age": 25,
}
'''

try:
    data = json.loads(invalid_json)
except json.JSONDecodeError as e:
    print("JSONDecodeError:", e)

JSONDecodeError: Expecting property name enclosed in double quotes: line 3 column 3 (char 5)

### Mini Exercise 

Fix the invalid JSON below:

```json
{
  region: "Central",
  "taxi_count": 120,
  "available": True,
}
```

Questions:

1. Which key is invalid?
2. Which boolean value is invalid?
3. Is there a trailing comma?

In [8]:
# Exercise: fix the JSON string

fixed_json = '''
{
  "region": "Central",
  "taxi_count": 120,
  "available": true
}
'''

data = json.loads(fixed_json)
pprint(data)

{'available': True, 'region': 'Central', 'taxi_count': 120}

## 7. Python `json` Library

Python has a built-in library called `json`.

Common functions:

| Function | Purpose |
|---|---|
| `json.loads()` | Convert JSON string to Python object |
| `json.dumps()` | Convert Python object to JSON string |
| `json.load()` | Read JSON from a file |
| `json.dump()` | Write JSON to a file |

Remember:

| Function | Input | Output |
|---|---|---|
| `loads` | JSON string | Python object |
| `dumps` | Python object | JSON string |
| `load` | File object | Python object |
| `dump` | Python object + file object | JSON file |

## 8. `json.loads()` and `json.dumps()`

`loads` means "load from string".

`dumps` means "dump to string".

In [9]:
json_text = '''
{
  "course": "Data Engineering",
  "day": 1,
  "topics": ["API", "JSON", "Parquet"]
}
'''

python_obj = json.loads(json_text)

print("After json.loads():")
print(type(python_obj))
pprint(python_obj)

json_string = json.dumps(python_obj, indent=2)

print("\nAfter json.dumps():")
print(type(json_string))
print(json_string)

After json.loads():
<class 'dict'>
{'course': 'Data Engineering', 'day': 1, 'topics': ['API', 'JSON', 'Parquet']}

After json.dumps():
<class 'str'>
{
  "course": "Data Engineering",
  "day": 1,
  "topics": [
    "API",
    "JSON",
    "Parquet"
  ]
}

### Note

`indent=2` makes the JSON output easier to read.

Without indentation, JSON is still valid but less readable.

In [10]:
compact_json = json.dumps(python_obj)
pretty_json = json.dumps(python_obj, indent=2)

print("Compact JSON:")
print(compact_json)

print("\nPretty JSON:")
print(pretty_json)

Compact JSON:
{"course": "Data Engineering", "day": 1, "topics": ["API", "JSON", "Parquet"]}

Pretty JSON:
{
  "course": "Data Engineering",
  "day": 1,
  "topics": [
    "API",
    "JSON",
    "Parquet"
  ]
}

## 9. `json.load()` and `json.dump()`

`load` and `dump` are used with files.

Let us save a Python object to a JSON file and read it back.

In [11]:
course_config = {
    "course_name": "Data Engineering",
    "duration_days": 5,
    "topics": [
        "API ingestion",
        "JSON",
        "Parquet",
        "SQL",
        "Airflow"
    ],
    "has_project": True
}

with open("course_config.json", "w", encoding="utf-8") as f:
    json.dump(course_config, f, indent=2)

print("Saved course_config.json")

Saved course_config.json

In [12]:
with open("course_config.json", "r", encoding="utf-8") as f:
    loaded_config = json.load(f)

pprint(loaded_config)

{'course_name': 'Data Engineering',
 'duration_days': 5,
 'has_project': True,
 'topics': ['API ingestion', 'JSON', 'Parquet', 'SQL', 'Airflow']}

## 10. Accessing JSON Fields

After JSON is converted into a Python dictionary or list, we access fields using normal Python syntax.

In [13]:
student = {
    "name": "Alice",
    "age": 25,
    "skills": ["Python", "SQL"],
    "address": {
        "country": "Singapore",
        "postal_code": "100001"
    }
}

print(student["name"])
print(student["skills"][0])
print(student["address"]["country"])

Alice
Python
Singapore

### Mini Question 

Given the following object:

```python
student = {
    "name": "Alice",
    "skills": ["Python", "SQL"],
    "address": {
        "country": "Singapore"
    }
}
```

How do we access:

1. `"Alice"`?
2. `"SQL"`?
3. `"Singapore"`?

In [14]:
# Answers

print(student["name"])
print(student["skills"][1])
print(student["address"]["country"])

Alice
SQL
Singapore

## 11. Nested JSON

Real API responses are often nested.

Example:

```json
{
  "timestamp": "2026-05-26T09:00:00",
  "region": "Central",
  "weather": {
    "condition": "Cloudy",
    "temperature": 30.5,
    "humidity": 78
  }
}
```

The `weather` field is another object inside the main object.

In [15]:
json_text = '''
{
  "timestamp": "2026-05-26T09:00:00",
  "region": "Central",
  "weather": {
    "condition": "Cloudy",
    "temperature": 30.5,
    "humidity": 78
  }
}
'''

data = json.loads(json_text)

print("Condition:", data["weather"]["condition"])
print("Temperature:", data["weather"]["temperature"])

Condition: Cloudy
Temperature: 30.5

## 12. Array of Objects

A very common API response pattern is an array of objects.

Example:

```json
[
  {"region": "Central", "taxi_count": 120},
  {"region": "East", "taxi_count": 85},
  {"region": "West", "taxi_count": 95}
]
```

This can be directly converted into a DataFrame.

In [16]:
json_text = '''
[
  {"region": "Central", "taxi_count": 120},
  {"region": "East", "taxi_count": 85},
  {"region": "West", "taxi_count": 95}
]
'''

data = json.loads(json_text)

df = pd.DataFrame(data)
df

    region  taxi_count
0  Central         120
1     East          85
2     West          95

### Mini Exercise 

Add one more region to the JSON array and convert it into a DataFrame.

Example new record:

```json
{"region": "North", "taxi_count": 70}
```

In [17]:
json_text = '''
[
  {"region": "Central", "taxi_count": 120},
  {"region": "East", "taxi_count": 85},
  {"region": "West", "taxi_count": 95},
  {"region": "North", "taxi_count": 70}
]
'''

data = json.loads(json_text)
df = pd.DataFrame(data)
df

    region  taxi_count
0  Central         120
1     East          85
2     West          95
3    North          70

## 13. Nested Array Example: Taxi Locations

Many real APIs return nested arrays.

For example, a taxi availability API may return:

```json
{
  "timestamp": "2026-05-26T09:00:00",
  "taxis": [
    {"lat": 1.3001, "lon": 103.8001},
    {"lat": 1.3102, "lon": 103.8102}
  ]
}
```

This is not a flat table yet.

In [18]:
taxi_json = '''
{
  "timestamp": "2026-05-26T09:00:00",
  "source": "sample_taxi_api",
  "taxis": [
    {"lat": 1.3001, "lon": 103.8001},
    {"lat": 1.3102, "lon": 103.8102},
    {"lat": 1.3203, "lon": 103.8203}
  ]
}
'''

taxi_data = json.loads(taxi_json)

rows = []

for taxi in taxi_data["taxis"]:
    rows.append({
        "timestamp": taxi_data["timestamp"],
        "source": taxi_data["source"],
        "latitude": taxi["lat"],
        "longitude": taxi["lon"]
    })

df_taxi = pd.DataFrame(rows)
df_taxi

             timestamp           source  latitude  longitude
0  2026-05-26T09:00:00  sample_taxi_api    1.3001   103.8001
1  2026-05-26T09:00:00  sample_taxi_api    1.3102   103.8102
2  2026-05-26T09:00:00  sample_taxi_api    1.3203   103.8203

## 14. Flattening JSON with `pandas.json_normalize()`


`pd.json_normalize()` is a useful pandas function for converting nested JSON into a flatter table format.

### Key Idea

In many cases， if the input is a list of JSON objects, then usually:

> each JSON object becomes one row.

Nested fields can be expanded into separate columns.

For example, a nested field such as:

`weather.condition`

can become a column in the table.

### Note

`json_normalize()` helps flatten nested JSON, but it does not decide the meaning of the data for us.

Before converting JSON into a table, we still need to ask:

> What should one row represent?

In [19]:
weather_records = [
    {
        "region": "Central",
        "weather": {
            "condition": "Cloudy",
            "temperature": 30.5,
            "humidity": 78
        }
    },
    {
        "region": "East",
        "weather": {
            "condition": "Rain",
            "temperature": 28.9,
            "humidity": 85
        }
    }
]

df_weather = pd.json_normalize(weather_records)
df_weather

    region weather.condition  weather.temperature  weather.humidity
0  Central            Cloudy                 30.5                78
1     East              Rain                 28.9                85

Notice how nested fields become columns such as:

```text
weather.condition
weather.temperature
weather.humidity
```

## 15. JSON Lines / NDJSON

Another important format is **JSON Lines**, also called **NDJSON**.

Instead of one big JSON array, each line is a separate JSON object.

Example:

```json
{"user_id": 1, "event": "click"}
{"user_id": 2, "event": "purchase"}
{"user_id": 3, "event": "logout"}
```

This is common in logs and streaming data.

Why it is useful:

| Reason | Explanation |
|---|---|
| Streaming-friendly | Can process one line at a time |
| Large-file friendly | No need to load the whole file |
| Log-friendly | Each event is one line |
| Easy to append | Add new events at the end |

In [20]:
json_lines_text = '''
{"user_id": 1, "event": "click"}
{"user_id": 2, "event": "purchase"}
{"user_id": 3, "event": "logout"}
'''.strip()

records = []

for line in json_lines_text.splitlines():
    records.append(json.loads(line))

df_events = pd.DataFrame(records)
df_events

   user_id     event
0        1     click
1        2  purchase
2        3    logout

### Mini Exercise 

Create a JSON Lines string with three taxi events.

Each line should contain:

- `taxi_id`
- `region`
- `available`
- `timestamp`

Then parse it into a DataFrame.

In [21]:
taxi_events_jsonl = '''
{"taxi_id": "T001", "region": "Central", "available": true, "timestamp": "2026-05-26T09:00:00"}
{"taxi_id": "T002", "region": "East", "available": true, "timestamp": "2026-05-26T09:00:00"}
{"taxi_id": "T003", "region": "West", "available": false, "timestamp": "2026-05-26T09:00:00"}
'''.strip()

records = [json.loads(line) for line in taxi_events_jsonl.splitlines()]

df_taxi_events = pd.DataFrame(records)
df_taxi_events

  taxi_id   region  available            timestamp
0    T001  Central       True  2026-05-26T09:00:00
1    T002     East       True  2026-05-26T09:00:00
2    T003     West      False  2026-05-26T09:00:00

## 16. GeoJSON

GeoJSON is a special JSON-based format for geospatial data.

It is commonly used to represent:

- Points
- Lines
- Polygons
- MultiPolygons
- Geospatial features
- Feature collections

GeoJSON is useful in data engineering when we work with maps, coordinates, regions, and spatial joins.

Example: a point location in GeoJSON:

```json
{
  "type": "Point",
  "coordinates": [103.8198, 1.3521]
}
```

Important:

> GeoJSON coordinates are usually written as `[longitude, latitude]`, not `[latitude, longitude]`.

Example: a simple region boundary in GeoJSON:

```json
{
  "type": "Feature",
  "properties": {
    "name": "Tampines"
  },
  "geometry": {
    "type": "Polygon",
    "coordinates": [
      [
        [103.9200, 1.3300],
        [103.9700, 1.3300],
        [103.9700, 1.3700],
        [103.9200, 1.3700],
        [103.9200, 1.3300]
      ]
    ]
  }
}

## 17. GeoJSON Feature

A GeoJSON feature combines geometry with properties.

Example:

```json
{
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [103.8198, 1.3521]
  },
  "properties": {
    "name": "Singapore",
    "category": "city"
  }
}
```

In [22]:
geojson_point = {
    "type": "Point",
    "coordinates": [103.8198, 1.3521]
}

print("GeoJSON type:", geojson_point["type"])
print("Longitude:", geojson_point["coordinates"][0])
print("Latitude:", geojson_point["coordinates"][1])

GeoJSON type: Point
Longitude: 103.8198
Latitude: 1.3521

In [23]:
geojson_feature = {
    "type": "Feature",
    "geometry": {
        "type": "Point",
        "coordinates": [103.8198, 1.3521]
    },
    "properties": {
        "name": "Singapore",
        "category": "city"
    }
}

print("Feature type:", geojson_feature["type"])
print("Geometry type:", geojson_feature["geometry"]["type"])
print("Name:", geojson_feature["properties"]["name"])
print("Longitude:", geojson_feature["geometry"]["coordinates"][0])
print("Latitude:", geojson_feature["geometry"]["coordinates"][1])

Feature type: Feature
Geometry type: Point
Name: Singapore
Longitude: 103.8198
Latitude: 1.3521

## 18. GeoJSON FeatureCollection

A FeatureCollection contains multiple features.

This is very common when representing many locations or many regions.

Example use cases:

| Use Case | GeoJSON Geometry |
|---|---|
| Taxi locations | Point |
| Road segments | LineString |
| Planning areas | Polygon |
| Country boundaries | MultiPolygon |

In [24]:
geojson_feature_collection = {
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [103.8001, 1.3001]
            },
            "properties": {
                "taxi_id": "T001",
                "region": "Central"
            }
        },
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [103.8102, 1.3102]
            },
            "properties": {
                "taxi_id": "T002",
                "region": "East"
            }
        }
    ]
}

rows = []

for feature in geojson_feature_collection["features"]:
    coordinates = feature["geometry"]["coordinates"]
    properties = feature["properties"]

    rows.append({
        "taxi_id": properties["taxi_id"],
        "region": properties["region"],
        "longitude": coordinates[0],
        "latitude": coordinates[1]
    })

df_geo = pd.DataFrame(rows)
df_geo

  taxi_id   region  longitude  latitude
0    T001  Central   103.8001    1.3001
1    T002     East   103.8102    1.3102

## 19. Summary

In this notebook, we learned:

1. JSON is a common format for APIs, logs, configuration, and semi-structured data.
2. JSON objects use `{}` and become Python dictionaries.
3. JSON arrays use `[]` and become Python lists.
4. JSON supports strings, numbers, booleans, null, objects, and arrays.
5. JSON syntax is strict: double quotes are required and trailing commas are not allowed.
6. Python's `json` library can parse and generate JSON.
7. Nested JSON often needs to be flattened before analytics.
8. JSON Lines is useful for logs and streaming-style data.
9. GeoJSON is a JSON-based format for geospatial data.